## creating 1_D array


In [2]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


## Creating 2-D array

In [4]:
import numpy as np
arr =np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)
print(type(arr))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
<class 'numpy.ndarray'>


## Creating 3-D array

In [9]:
import numpy as np
arr = np.array([[[1,2,3,4,5],[6,7,8,9,10]], [[11,12,13,14,15], [16,17,18,19,20]]])
print(arr)
## checking the type 
print(type(arr))
## chceking the dimention
print(arr.ndim)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]
<class 'numpy.ndarray'>
3


In [12]:
## creating 5-D 
arr = np.array([1,2,3,4,5], ndmin = 5)
print(arr)
print('numbers of dimentions: ', arr.ndim)

[[[[[1 2 3 4 5]]]]]
numbers of dimentions:  5


## Numpy indexing

In [2]:
## accessing an array element
# accessing the 5th element
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr[4])

5


In [4]:
## accessing 2 elements
arr=np.array([1,2,3,4,5,6])
print(arr[1] + arr[3])

6


In [8]:
## accessing 2 elements in 2-D array
arr = np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(arr[1][2]+[0])


[8]


## Slicing Arrays

### this means taking elements from one given index to another index

### start:end
### start:
### :end
### start:end:step

In [9]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8])
## NB, the results include start index but exclude end index
print(arr[1:5])

[2 3 4 5]


In [10]:
## slice elements from index 4 to the end
arr = np.array([1,2,3,4,5,6,7,8])
print(arr[4:])

[5 6 7 8]


In [11]:
## Slice elements from the beginning to index 4 (not included):
arr = np.array([1,2,3,4,5,6,7,8])
print(arr[:4])

[1 2 3 4]


### Negative slicing

In [12]:
## Slice from the index 3 from the end to index 1 from the end:
arr = np.array([1,2,3,4,5,6,7,8])
print(arr[-3:-1])

[6 7]


## Use of Step

In [13]:
## Return every other element from index 1 to index 5:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8])
print(arr[1:5:2])

[2 4]


In [16]:
## Return every other element from the entire array:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8])
print(arr[::3])

[1 4 7]


In [19]:
## 2-D sclicing 
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1,1:3])


[7 8]


## DATA TYPES

In [2]:
## check data type of an array
import numpy as np
arr = np.array([10,20,30,40])
print(arr.dtype)

int64


## Unicode strings
import numpy as np
arr = np.array(["Apple", "Oranges", "Mangos"])
print(arr.dtype)

In [8]:
# Strings
import numpy as np
arr = np.array([100,200,300,400], dtype ='S')
print(arr.dtype)

|S3


In [9]:
import numpy as np
arr = np.array([10,20,30,40], dtype='i4')
print(arr.dtype)

int32


## Not converted integers

In [12]:
import numpy as np

arr = np.array(['a', '2', '3', '4'], dtype='i')## error

array([1, 2, 3, 4], dtype=int32)

## NumPy Array Copy vs View

In [1]:
## Copy
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [2]:
## View
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


## NumPy Array Shape

In [14]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr)
print(arr.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [10]:
import numpy as np
arr =np.array([1,2,3,4], ndmin = 5)
print(arr)
arr.shape

[[[[[1 2 3 4]]]]]


(1, 1, 1, 1, 4)

## NumPy Array Reshaping

In [12]:
## Reshape From 1-D to 2-D
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


## NumPy Array Iterating

In [17]:
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8]])
for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6
7
8


## NumPy Sorting Arrays

In [19]:
import numpy as np
arr = np.array([[4,2,3,1],[6,5,7,8]])
print(np.sort(arr))

[[1 2 3 4]
 [5 6 7 8]]
